# Generated by Django 5.2.7 on 2025-10-25 15:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='product_file'),
        ),
    ]
